import Head from "next/head";
import { getPageConfig } from "@/helpers/getPageConfig";

const content = {
    en: "This is the second page",
    fi: "Tämä on toinen sivu",
}

export default function Home({ config, locale }) {
  const { footer: {[locale]: footerData } } = config;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          {content[locale]}
        </main>
        <footer>{footerData.text}</footer>
      </div>
    </>
  );
}

export async function getStaticProps({ locale }) {
    return {
        props: {
          config: getPageConfig(),
          locale,
        },
    };
}